#!/bin/bash

# Constants {{{1
################################################################

PROG_PATH=$(dirname $0)

# MAIN {{{1
################################################################

$PROG_PATH/../biosigner_wrapper.R dataMatrix_in $PROG_PATH/../test-data/dataMatrix.tsv sampleMetadata_in $PROG_PATH/../test-data/sampleMetadata.tsv variableMetadata_in $PROG_PATH/../test-data/variableMetadata.tsv respC gender opcC full methodC all bootI 5 tierC S pvalN 0.05 seedI 123 variableMetadata_out $PROG_PATH/outputVariableMetadata.tsv

if ! diff "$PROG_PATH/outputVariableMetadata.tsv" "$PROG_PATH/../test-data/variableMetadata.out" ; then
	echo "Incorrect output variable metadata." >&2
	exit 1
fi
